# Generated by Django 5.1 on 2024-08-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookAccount',
            new_name='BankAccount',
        ),
    ]
