# Generated by Django 5.1 on 2024-08-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountHolder', '0001_initial'),
        ('BankAccount', '0002_rename_bookaccount_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountHolder.accountholder'),
        ),
    ]
