# Generated by Django 5.1 on 2024-08-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountHolder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='NID',
            field=models.CharField(max_length=20),
        ),
    ]
